FROM mcr.microsoft.com/dotnet/sdk:2.1 AS build
WORKDIR /src
COPY CoreWithNUnit.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/sdk:2.1
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "CoreWithNUnit.dll"]